### ISSUE TITLE
lerp_angle

### ISSUE THREAD

**Issue by Gizmo199** [Alphish/gm-community-toolbox#15]
This allows you to lerp between 2 different angles while maintaining a value between 0 and 360 and avoiding the 'lerp wrap around' issue with using a traditional `lerp` function on angles. Uses mercenaries `modulo` technique to keep values wrapped properly.
```js
/// @func lerp_angle(angle1, angle2, amount)
/// @arg angle1
/// @arg angle2
/// @arg amount
/// @desc lerp an angle to another angle. The angle returned will always be a number between 0 and 360.
/// @returns {number}
function lerp_angle(_angle1, _angle2, _amount){
	return ((_angle1 + ( angle_difference(_angle2, _angle1) * _amount )) % 360 + 360 ) % 360;
}
```

Example (works with negative angle inputs as well)
```js
angle_to = point_direction(x, y, mouse_x, mouse_y);
image_angle = lerp_angle(image_angle, angle_to, .3);
```

**Comment by Alphish** [comment]
Since the feature is reasonably popular and I can't think of a better name of [icode]lerp_angle[/icode] (even more so with [icode]approach[/icode] and [icode]approach_angle[/icode] using the same convention), I'm going to skip the name voting and accept it for implementation under [icode]lerp_angle[/icode] name. As usual, if someone wants to pick it up for implementation, please comment here so others can coordinate.

The tests should check various angle approaching scenarios, like:
- simple angle increase (without crossing the 0/360 angle boundary)
- simple angle decrease
- crossing 0/360 angle boundary while increasing angle
- crossing 0/360 angle boundary while decreasing angle
- lerping angle when its already at the destination

Also, the result should always be between 0 and 360.

As for the demo, it might be good to build upon the demo from issue #3 (`approach`/`approach_angle`), where the rotating turret things can follow the mouse using either `approach` or `approach_angle`. Perhaps the demo would switch between `lerp` and `approach` mode, and the demo entities would switch between `lerp`/`lerp_angle` and `approach`/`approach_angle`?

So it might be good to prioritise the `approach`/`approach_angle` feature, merge it and then build `lerp_angle` upon that.

**Comment by Alphish** [comment]
Heads up: I'm going to do this and `approach`/`approach_angle` (from issue #3).

**Comment by Alphish** [comment]
PR has been merged!
