### ISSUE TITLE
shader_set_uniform_color()

### ISSUE THREAD

**Issue by glebtsereteli** [Alphish/gm-community-toolbox#22]
## Definition
```js
/// @func shader_set_uniform_color()
/// @param {Id.Uniform} uniform
/// @param {Constant.GMColor} color
/// @param {Real} [alpha=1]
/// @desc Shortcut for passing a vec4 color uniform to a shader.
function shader_set_uniform_color(_uniform, _color, _alpha = 1) {
    var _r = color_get_red(_color) / 255;
    var _g = color_get_green(_color) / 255;
    var _b = color_get_blue(_color) / 255;
    shader_set_uniform_f(_uniform, _r, _g, _b, _alpha);
}
```
## Example
```js
shader_set(shd_outline);
// Passing other uniforms here...
var _u_color = shader_get_uniform(shd_outline, "u_color");
shader_set_uniform_color(_u_color, c_red, 0.5);
draw_self();
shader_reset();
```

**Comment by Alphish** [comment]
I personally don't use shaders much, but the function fits well with other `shader_set_uniform_*(...)` functions, so if other shader users give it enough upvotes - sure, why not?

**Comment by Alphish** [comment]
Since enough people upvoted this, we can go ahead and add this. The function can be added as presented here, except the JSDoc order should be `@func` / `@desc` / `@arg`. Please add this to utils_Shader script, next to utils_Math and utils_Misc.

Currently, we have no way feasible way of testing visuals, so let's skip tests here.

The demo should feature some colour-dependent shader (might even be the outline shader implied in the original post) applied to some sprite, and something to change colours and alpha (e.g. sliders).

As always, if someone wants to pick this up, please make a comment here so multiple people won't start work on it independently.

**Comment by Mercerenies** [comment]
If your concern is testing, then [`surface_getpixel`](https://manual.yoyogames.com/GameMaker_Language/GML_Reference/Drawing/Surfaces/surface_getpixel.htm) might be your friend. Set up a shader, draw a simple object to a surface, and then check that a given pixel (or several) is what you expect.

**Comment by dicksonlaw583** [comment]
Since the function is ready and we are skipping unit testing for now, I am picking up this ticket so that @Alphish can focus on the initial release.

**Comment by Alphish** [comment]
Approved and merged.
