### ISSUE TITLE
Positive modulo

### ISSUE THREAD

**Issue by Mercerenies** [Alphish/gm-community-toolbox#4]
Here's a short function that I throw in every project I ever write, pretty much. The built-in Game Maker modulo operator % takes the sign of the dividend, matching the behavior of C. This can cause awkwardness when using % to perform wrapping behavior on a value that might be negative. This is a variant of the modulo function that matches the sign of the result to the sign of the *divisor*.

```
function modulo(a, b) {
  return (a % b + b) % b;
}
```

**Comment by Alphish** [comment]
Generally in favour of this one, and for the `div` counterpart as well (i.e. div that rounds towards -infinity, instead of towards 0).

Wondering about the name. `modulo` doesn't quite show how it's set apart from the `mod` keyword.

Reading about division, there's apparently the concept of Euclidean division which more or less matches :
https://en.wikipedia.org/wiki/Euclidean_division

So I consider function names like:
- `mod_euclidean` and `div_euclidean` (kinda mouthful, and people might not quite know what Euclidean division is supposed to be)
- `eucmod` and `eucdiv` (terser, but still relies on knowledge of Euclidean division)
- `math_mod` and `math_div` (as in, the way mathematicians handle modular arithmetics)

We might need to accept the fact that there's no super-intuitive name that would make users go "oh, yes, it's the kind of mod/div that handles negative values properly!" and explain things in JSDoc instead. Still, other name suggestions welcome.

**Comment by JonathanHackerCG** [comment]
I agree with this suggestion. As for name in my own code, I opted for the ``emod`` and ``ediv`` (even terser).

If you want to avoid relying on knowing about "Euclidean", I would suggest ``mod_positive`` or some variation of that.

**Comment by Mercerenies** [comment]
Actually I'm fond of `eucmod` and `eucdiv` now that you say that. It's short enough to still type easily, but long enough that anyone who *knows* what Euclidean division is will immediately recognize the prefix.

**Comment by Alphish** [comment]
Alright, then maybe let's do some voting on the naming? Since `emod`/`ediv` and `eucmod`/`eucdiv` seem to be most popular:
- 🎉 for `emod`/`ediv`
- 🚀 for `eucmod`/`eucdiv`
- 😕 for something else altogether

People seem to agree that it would be a nice addition, and it seems naming is the only remaining thing to settle before proceeding with implementation.

**Comment by devKathy** [comment]
I will go ahead and say that I am starting the implementation work. I will let folks know if any issues arise.

I'm adjusting Merc's algorithm to be correct with Euclidian division mods in the case of negative divisors. It seems to me that what he has as of now is based on floor division.

 ```
function eucmod(a, b) {
	b = abs(b);
  return (a % b + b) % b;
} 
```

For more on Euclidian/floor division, see (Look especially at the C implementations!):
https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/divmodnote.pdf

You can see people doing various implementations of floor division here:
https://stackoverflow.com/questions/10065080/mod-explanation?rq=3

Take care, folks! :)

**Comment by Alphish** [comment]
The related PR has been merged, and thus I'm closing this issue.
