### ISSUE TITLE
JSON file loading and saving

### ISSUE THREAD

**Issue by dicksonlaw583** [Alphish/gm-community-toolbox#9]
You explicitly requested these in [the original thread](https://forum.gamemaker.io/index.php?threads/gamemaker-community-toolbox-project.103966/#post-627162), so here they are.

A lot of rookies are not using JSON to its fullest power because these functions aren't built-in, and I often have to repeat myself about these functions to explain to them that loading and saving JSON files isn't something to be afraid of.

```gml
///@func json_load_file(filename)
///@param {String} filename The name of the JSON file to load from.
///@desc Load the given JSON file and return its parsed result.
function json_load_file(filename) {
    var buffer = buffer_load(filename);
    var fileContent = buffer_read(buffer, buffer_string);
    buffer_delete(buffer);
    var result = json_parse(fileContent);
    return result;
}
```

```gml
///@func json_save_file(filename, value)
///@param {String} filename The name of the JSON file to save to.
///@param {Struct,Array,String,Real,Bool,Undefined} value The value to save.
///@desc Encode the given value as JSON and save the result into the given JSON file.
function json_save_file(filename, value) {
    var result = json_stringify(value);
    var buffer = buffer_create(string_byte_length(result), buffer_fixed, 1);
    buffer_write(buffer, buffer_text, result);
    buffer_save(buffer, filename);
    buffer_delete(buffer);
}
```

**Comment by Alphish** [comment]
Another one I hoped to include, eventually. :wink:

In [another issue](https://github.com/Alphish/gm-community-toolbox/issues/10), I suggested functions for reading/writing text files as string, which would take care of all the buffer reading. Then the JSON loading/saving functions could use these, like in another two of my copy-pasted functions:

```gml
/// @function json_load(filename)
/// @description Loads a given JSON file into a GML value (struct/array/string/real).
/// @param {String} filename        The path of the JSON file to load.
function json_load(_filename) {
    var _json_content = file_read_all_text(_filename);
    if (is_undefined(_json_content))
        return undefined;
    
    try {
        return json_parse(_json_content);
    } catch (_) {
        // if the file content isn't a valid JSON, prevent crash and return undefined instead
        return undefined;
    }
}

/// @function json_save(filename,value)
/// @description Saves a given GML value (struct/array/string/real) into a JSON file.
/// @param {String} filename        The path of the JSON file to save.
/// @param {Any} value                The value to save as a JSON file.
function json_save(_filename, _value) {
    var _json_content = json_stringify(_value);
    file_write_all_text(_filename, _json_content);
}
```

One notable feature of my implementation is that it doesn't crash when the JSON file is non-existing or invalid, and returns `undefined` instead. We're dealing with what would most likely become save files, which then some users would want to manipulate and accidentally make the file invalid, so preventing crashes in this situation might be preferable.

Also, I prefer `json_save` and `json_load` over `jsonsave_file` and `json_load_file`, since saving/loading to me already implies working with files 99% of the time. I wonder what's other's opinion about it.

**Comment by Alphish** [comment]
The feature has been accepted for development!

It should include two functions in `utils_Json` script:
- `json_load(filename)` function for loading a value from JSON
- `json_save(filename,value,[prettyprint])` function for saving a value into a JSON file (with optional pretty-print)

`json_load` tests should check loading different types of value (null, bool, number, string, array, struct). Most of these aren't covered by a nice fluent interface thing, so instead of using fluent assertion structures you can opt for direct `assert_equal` or `assert_that` assertions, I guess.

`json_save` would save file which might lead to weirdness if tests aren't cleaned up properly, so it won't be tested.

The demo should expand the file utilities demo by adding "Load JSON", "Save JSON" and "Save JSON (pretty)" (or maybe a checkbox for saving JSON, but we don't yet have a full-fledged checkbox control).
After loading JSON, the text area should be replaced with a pretty-printed value of the JSON, or "<could not read or parse JSON file>" if `json_load` returns undefined (if JSON contains "null", it will be parsed to `pointer_null` instead, so there's no conflict here).
After saving JSON, a JSON file should be created at a given location (duh!).

As usual, if someone wants to implement this, please post here to let others now.

**Comment by dicksonlaw583** [comment]
I'll take this one for now. Should be a minor adaptation of the File Utilities demo.

**Comment by dicksonlaw583** [comment]
The PR is now available: #49

Please note that I was not able to get loading a file containing only `null` to work, because `json_parse("null")` crashes under Runtime 2023.4.0.113. The PR does not contain the test for that.

**Comment by Alphish** [comment]
The PR has been accepted and merged, thank you for your contribution! ^^

**Comment by Alphish** [comment]
Also also, I made the issue #50 for moving the text areas from File/JSON utilities demos into its own control.
