### ISSUE TITLE
array_return_random

### ISSUE THREAD

**Issue by Kezarus-tech** [Alphish/gm-community-toolbox#91]
A simple way to return a random element from an array. Also have a default option if the array is empty.

```
function array_return_random(wArray, wDefault=undefined){
	if( array_length(wArray) <= 0 ){
		return wDefault;
	}else{
		return wArray[irandom_range(0, array_length(wArray)-1)];
	}
}
```

**Comment by Alphish** [comment]
Seems to be handled by function already in the Toolbox: [array_get_random](https://github.com/Alphish/gm-community-toolbox/blob/main/Docs/Reference/Functions/array_get_random.md). There's also a counterpart that removes the returned item, [array_pop_random](https://github.com/Alphish/gm-community-toolbox/blob/main/Docs/Reference/Functions/array_pop_random.md).

The case for the default option may be handled by the `??` operator which returns the right-hand side if the left-hand side is `null` or `undefined`, since `array_get_random` returns undefined for an empty array. For example:
```gml
var _random_number = array_get_random(numbers_array) ?? -1;
```

**Comment by Kezarus-tech** [comment]
Well, more often than not, you do not want to "pop" the element on the array.

**Comment by Alphish** [comment]
In my cases, I stumbled upon the need to "pop" a random element on quite a few occasions. ^^'
(especially with some kind of spawner things that would cycle through shuffled arrays of enemies)

But also, for those different kinds of purposes we have both `array_get_random` and `array_pop_random`, depending on what one needs at the moment. ;)

**Comment by Kezarus-tech** [comment]
Well, I would rather have protections built-in on my functions rather than rely on the placement of "??" and it's good for readability too. Maybe put an optional value on array_get_random() that can change its behavior (returning a default).

But, then again, we already have 2 other default values on array_get_random(), so I'm not 100% sold on the idea too...

**Comment by Appsurdgames** [comment]
In my humble opinion, `array_get_random` already works sufficiently well. 

If your array is empty and undefined is returned, you could explicitly check for that:

```
val = array_get_random(my_array);
if (val == undefined)
{
  val = "";
}
```
