### ISSUE TITLE
struct_get_value

### ISSUE THREAD

**Issue by Kezarus-tech** [Alphish/gm-community-toolbox#93]
A simple way to get a variable out of an struct and default value if the variable doesn't exists.

```
function struct_get_value(wStruct, variableName, defaultValue){
	if( variable_struct_exists(wStruct, variableName) ){
		return variable_struct_get(wStruct, variableName);
	}else{
		return defaultValue;
	}
}
```

**Comment by Alphish** [comment]
I think current `struct_get` combined with the null-coalescence operator `??` work well enough that no extra function is needed.
E.g. `var _name = struct_get(_config, "name") ?? "MAIN";`

**Comment by tabularelf** [comment]
I really don't get why `struct_get(struct, "key") ?? 32` wouldn't suffice?

**Comment by Kezarus-tech** [comment]
One word: readability.

It's just good practice, as on Clean Code, you make code as readable as possible. If you just want to check the value and send it to another function, and not a variable, you can also do it without much os a fuss.

But, hey, it's a toolbox and we don't need to use every tool on it. It's meant to be useful for some situations.

**Comment by tabularelf** [comment]
That I can understand, but I find `??` to be readable enough to me as is. 😆
I feel a better name would be `struct_get_default`, since you are specifying a specific default value if it doesn't exist imo!

**Comment by Kezarus-tech** [comment]
Yeah, it's your opinion about it. I get it.

But code readability refers to how easily a developer (including your future self!) can understand, navigate, and maintain the code. Readable code reduces cognitive load, makes debugging easier, and enhances collaboration among team members.

For simple checks, sure "??" is not that harmful. But a named function improves:

1. Self-Documentation
2. Reusability
3. Extendability
4. Debugging

And, then again, it's a tool in the toolbox. It's meant to be useful, so there is no need to use a hammer on a screw.

**Comment by tabularelf** [comment]
I still call for `struct_get_default` and `struct_get_default_from_hash`.

**Comment by Kezarus-tech** [comment]
struct_get_default sounds good.

**Comment by Kezarus-tech** [comment]
I agree that handling every permutation in a function might be overkill—that's not the intention here. On one hand, GML doesn’t make it easy to identify or type classes. On the other, this approach helps keep your code clean by setting default values for variables before computation. While this is a single example, we often deal with multiple variables, not just one. Overusing "??" in such cases can make the code messy and harder to read.

That said, if you don’t find it useful, feel free to skip it. It’s just a tool I find helpful and have learned to use as part of industry standards.

**Comment by Alphish** [comment]
I would rather avoid making get_default variations for every function that may potentially return a non-result, although *interms of API design* I wouldn't mind if it was limited to plain collection access, like array_get or struct_get.

However, I would avoid adding these functions for performance reasons. The ?? short-circuits before trying to evaluate the default expression, whereas passing the default into a function requires it to be calculated before we even know it's needed. So something like `struct_get_or_default(bigstuff, "whatever", new BigBigStruct("whatever"))` might end up much slower than `struct_get(bigstuff, "whatever") ? ? new BigBigStruct("whatever")`.

Given these performance implications, I'd rather teach people to use the ?? operator for their defaults, rather than present a function that might lead users to potentially expensive solutions when a cheaper one is readily available. It doesn't matter for more trivial scenarios, but it's easier to consistently use more-or-equally performant scenario than to make decision every time, whether I want nicer looking _or_default function or more performant ?? operator.

**Comment by tabularelf** [comment]
To further add to it, we also lose entire compile-time optimisations. As we know with modern versions, any constant strings. i.e. `struct_get(struct, "foo")` become `struct_get_from_hash(struct, hash_of_foo)`, which is really nice for an extra boost of performance. `struct_get_default` doesn't gain any of those optimisations, so we actually lose out.
